function get_modules()
{
return
{
 "numbers":
 {
  "buttons":
  [
   [["1","ircode","KEY_1"],["2","ircode","KEY_2"],["3","ircode","KEY_3"]],
   [["4","ircode","KEY_4"],["5","ircode","KEY_5"],["6","ircode","KEY_6"]],
   [["7","ircode","KEY_7"],["8","ircode","KEY_8"],["9","ircode","KEY_9"]],
   [["-","ircode","KEY_MINUS"],["0","ircode","KEY_0"],["E","ircode","KEY_OK"]]
  ],
  "needed":["KEY_1","KEY_2","KEY_3","KEY_4","KEY_5","KEY_6","KEY_7","KEY_8","KEY_9","KEY_0"],
  "skip":false
 },
 "directions":
 {
  "buttons":
  [
    [[],["&#9652;","ircode","KEY_UP"],[]],
    [["&#9666;","ircode","KEY_LEFT"],["OK","ircode","KEY_OK"],["&#9656;","ircode","KEY_RIGHT"]],
    [[],["&#9662;","ircode","KEY_DOWN"],[]]
  ],
  "needed":["KEY_UP","KEY_DOWN","KEY_LEFT","KEY_RIGHT"],
  "skip":false
 },
 "navigator":
 {
  "buttons":
  [
   [["&#x23EA;","ircode","KEY_FASTREWIND"],["&#9654;","ircode","KEY_PLAY"],["&#x23E9;","ircode","KEY_FASTFORWARD"]],
   [["&#x23EE;","ircode","ircode","KEY_PREVIOUS"],[],["&#x23ED;","ircode","KEY_NEXT"]],
   [["&#x23FA;","ircode","KEY_RECORD"],["&#x23F8;","ircode","KEY_PAUSE"],["&#x23F9;","ircode","KEY_STOP"]]
  ],
  "needed":["KEY_PLAY","KEY_FASTREWIND","KEY_FASTFORWARD","KEY_PREVIOUS","KEY_NEXT","KEY_PAUSE"],
  "skip":false
 },
 "navigator2":
 {
  "buttons":
  [
   [["&#x23EA;","ircode","KEY_FASTREWIND"],["&#x23ef;","ircode","KEY_PAUSE"],["&#x23E9;","ircode","KEY_FASTFORWARD"]],
   [["&#x23EE;","ircode","KEY_PREVIOUS"],[],["&#x23ED;","ircode","KEY_NEXT"]],
   [["&#x23FA;","ircode","KEY_RECORD"],[],["&#x23F9;","ircode","KEY_STOP"]]
  ],
  "needed":["KEY_FASTREWIND","KEY_FASTFORWARD","KEY_PAUSE"],
  "skip":true
 },
 "channels":
 {
  "buttons":
  [
   [["Ch+","ircode","KEY_CHANNELUP"]],
   [["Ch"]],
   [["Ch-","ircode","KEY_CHANNELDOWN"]],
   [["Ch&#x21BA;","ircode","KEY_CHANNELPREVIOUS"]]
  ],
  "needed":["KEY_CHANNELUP","KEY_CHANNELDOWN"],
  "skip":true
 },
 "volume":
 {
  "buttons":
  [
   [["&#x1F50A;+","ircode","KEY_VOLUMEUP"]],
   [["&#x1F50A;Vol"]],
   [["&#x1F50A;-","ircode","KEY_VOLUMEDOWN"]],
   [["&#x1F507;","ircode","KEY_MUTE"]]
  ],
  "needed":["KEY_VOLUMEUP","KEY_VOLUMEDOWN"],
  "skip":true
 },
 "common":
 {
  "buttons":
  [
   [["Home","ircode","KEY_HOME"],["List","ircode","KEY_LIST"],["Exit","ircode","KEY_EXIT"],
   ["Menu","ircode","KEY_MENU"],["Guide","ircode","KEY_GUIDE"],["Info","ircode","KEY_INFO"]]
  ],
  "needed":[],
  "skip":true
 },
 "colors":
 {
  "buttons":
  [
   [
    ["&lt;font color=&quote;red&quote;&gt;&#x25A0;&lt;/font&gt;","ircode","KEY_RED"]
   ,["&lt;font color=&quote;green&quote;&gt;&#x25A0;&lt;/font&gt;","ircode","KEY_GREEN"]
   ,["&lt;font color=&quote;yellow&quote;&gt;&#x25A0;&lt;/font&gt;","ircode","KEY_YELLOW"]
   ,["&lt;font color=&quote;#0000FF&quote;&gt;&#x25A0;&lt;/font&gt;","ircode","KEY_BLUE"]]
  ],
  "needed":[],
  "skip":true
 },
 "power":
 {
  "buttons":
  [
   [["Power","ircode","KEY_POWER"],["On","ircode","KEY_POWERON"],["Off","ircode","KEY_POWEROFF"]]
  ],
  "needed":[],
  "skip":true
 },
 "catchall":{"buttons":"REST","needed":[],"skip":false}
};
}
